name: Build app Ubuntu

on:
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Current date
        id: current-date
        run: |
          echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo $CURRENT_DATE

      - name: Install Android SDK build tools
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "build-tools;30.0.3"

      - name: Add apksigner to PATH & Test
        run: |
          ls ${ANDROID_HOME}/build-tools/30.0.3/
          echo "export PATH=\$PATH:${ANDROID_HOME}/build-tools/30.0.3/" >> $GITHUB_ENV
          ${ANDROID_HOME}/build-tools/30.0.3/apksigner --version

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Allow execute Gradlew
        run: chmod +x gradlew

      - name: Decode SIGNING_KEY
        run: |
          mkdir -p app/keystore
          echo ${{ secrets.SIGNING_KEY }} | base64 --decode > app/keystore/signing_key.jks

      - name: Build + Move APK
        run: |
          ./gradlew assembleReleaseGH
          ls app/build/outputs/apk/release
          mkdir -p signedrelease/
          mv app/build/outputs/apk/release/iFunnyGHRelease.apk  signedrelease/iFunnyGHRelease.apk
        env:
          ALIAS: ${{ secrets.ALIAS }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Verify APK + Rename
        run: |
          ${ANDROID_HOME}/build-tools/30.0.3/apksigner verify --print-certs signedrelease/iFunnyGHRelease.apk
          mv signedrelease/iFunnyGHRelease.apk signedrelease/iFunnyDL-${{env.CURRENT_DATE}}.apk

      - name: Hash
        run: |
          sha256sum signedrelease/iFunnyDL-${{env.CURRENT_DATE}}.apk
          sha256sum signedrelease/iFunnyDL-${{env.CURRENT_DATE}}.apk > signedrelease/iFunnyDL-${{env.CURRENT_DATE}}.sha256

      - name: Artifact signed APK
        uses: actions/upload-artifact@v3
        with:
          name: iFunnyDLsigned
          path: |
            signedrelease/iFunnyDL-${{env.CURRENT_DATE}}.apk
            signedrelease/iFunnyDL-${{env.CURRENT_DATE}}.sha256

      - name: Release APK
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            iFunnyDL-${{ env.CURRENT_DATE }}.apk
          body: " \n\nDownload ``iFunnyDL-${{ env.CURRENT_DATE }}.apk`` and install it on your Android device. Share an iFunny post to the app or paste a link into the URL box and it'll download it to Pictures/iFunnyDL."
          append_body: true
          draft: false
          prerelease: false
        if: github.event_name == 'release'