name: Build app

on:
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Allow execute Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: iFunnyDL.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  upload-release:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v2
        with:
          name: iFunnyDL.apk

      - name: Upload APK to release
        uses: softprops/action-gh-release@v1
        with:
          files: iFunnyDL-release.apk