name: Build app

on:
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

env:
  CURRENT_DATE: ${{ steps.current-date.outputs.date }}  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Allow execute Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Move + Rename APK
        run: mv app/build/outputs/apk/debug/app-debug.apk iFunnyDL-$CURRENT_DATE.apk

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: iFunnyDLAPK
          path: iFunnyDL-$CURRENT_DATE.apk

  upload-release:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:

      - name: Upload APK to release
        uses: softprops/action-gh-release@v1
        with:
          files: iFunnyDL-$CURRENT_DATE.apk