name: Build app

on:
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current date
        id: current-date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Decode cutestore
        run: |
          echo "${{ secrets.IFKEYSTORE }}" | base64 --decode > release-key.jks
        shell: bash
        env:
          KEYSTOREFILE: release-key.jks

      - name: Print date
        run: echo $CURRENT_DATE

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Allow execute Gradlew
        run: chmod +x gradlew

      - name: Build and sign APK
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_FILE: release-key.jks
          KEYSTORE_PASSWORD: ${{ secrets.IFKEYPASS }}
          KEY_ALIAS: ${{ secrets.KEYALIAS }}
          KEY_PASSWORD: ${{ secrets.IFKEYPASS }}

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Move + Rename APK
        run: |
          mv app/build/outputs/apk/debug/app-debug.apk iFunnyDL-Debug-$CURRENT_DATE.apk
          mv app/build/outputs/apk/release/app-release.apk iFunnyDL-$CURRENT_DATE.apk

      - name: Upload Debug artifact
        uses: actions/upload-artifact@v3
        with:
          name: iFunnyDL-Debug
          path: iFunnyDL-Debug-${{ env.CURRENT_DATE }}.apk

      - name: Upload Release artifact
        uses: actions/upload-artifact@v3
        with:
          name: iFunnyDL-Release
          path: iFunnyDL-${{ env.CURRENT_DATE }}.apk

      - name: Release APK
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            iFunnyDL-${{ env.CURRENT_DATE }}.apk
          body: " \n\nDownload ``iFunnyDL-${{ env.CURRENT_DATE }}.apk`` and install it on your android device. Share an iFunny post to the app or paste a link into the URL box and it'll download it to Pictures/iFunnyDL."
          append_body: true
          draft: false
          prerelease: false
        if: github.event_name == 'release'