name: Build app Ubuntu

on:
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Current date
        id: current-date
        run: |
          echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo $CURRENT_DATE

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install Android SDK build tools
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "build-tools;30.0.3"

      - name: Allow execute Gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: |
          ./gradlew assembleRelease

      - name: Move APK
        run: |
          mkdir -p signedrelease/
          mv app/build/outputs/apk/release/app-release.apk signedrelease/app-release.apk

      - name: Sign APK
        run: |
          echo ${{ secrets.SIGNING_KEY }} | base64 --decode > signing_key.jks
          apksigner sign --ks signing_key.jks --ks-pass ${{ secrets.KEYSTORE_PASSWORD }} --key-pass ${{ secrets.KEY_PASSWORD }} signedrelease/app-release.apk
          mv signedrelease/app-release.apk signedrelease/iFunnyDL-${{env.CURRENT_DATE}}.apk

      - name: Hash
        run: |
          sha256sum signedrelease/iFunnyDL-${{env.CURRENT_DATE}}.apk
          sha256sum signedrelease/iFunnyDL-${{env.CURRENT_DATE}}.apk > signedrelease/iFunnyDL-${{env.CURRENT_DATE}}.sha256

      - name: Artifact signed APK
        uses: actions/upload-artifact@v3
        with:
          name: iFunnyDLsigned
          path: |
            signedrelease/iFunnyDL-${{env.CURRENT_DATE}}.apk
            signedrelease/iFunnyDL-${{env.CURRENT_DATE}}.sha256

      - name: Release APK
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            iFunnyDL-${{ env.CURRENT_DATE }}.apk
          body: " \n\nDownload ``iFunnyDL-${{ env.CURRENT_DATE }}.apk`` and install it on your android device. Share an iFunny post to the app or paste a link into the URL box and it'll download it to Pictures/iFunnyDL."
          append_body: true
          draft: false
          prerelease: false
        if: github.event_name == 'release'