name: Build app

on:
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current date
        id: current-date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Print date
        run: echo ${{ steps.current-date.outputs.date }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Allow execute Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Move + Rename APK
        run: mv app/build/outputs/apk/debug/app-debug.apk iFunnyDL-${{ steps.current-date.outputs.date }}.apk

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: iFunnyDLzip
          path: iFunnyDL-${{ steps.current-date.outputs.date }}.apk

      - name: Upload APK to release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: iFunnyDL-${{ steps.current-date.outputs.date }}.apk
          asset_name: iFunnyDL-${{ steps.current-date.outputs.date }}.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Release APK
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            iFunnyDL-${{ steps.current-date.outputs.date }}.apk
          body: " \n\nDownload ``iFunnyDL-${{ steps.current-date.outputs.date }}.apk`` and install it on your android device. Share an iFunny post to it or paste into box and it'll download it to Pictures/iFunnyDL."
          append_body: true
          draft: false
          prerelease: false
        if: github.event_name == 'release'
