name: Build app windows

on:
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current date
        id: current-date
        run: echo "CURRENT_DATE=$(Get-Date -Format 'yyyyMMdd')" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: powershell

      - name: Print date
        run: echo $CURRENT_DATE

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Figure out structure
        run: dir

#      - name: Build with Gradle
#        run: .\gradlew :app:assembleDebug

      - name: Move + Rename APK
        run: |
          move app\build\outputs\apk\debug\app-debug.apk iFunnyDL-$env:CURRENT_DATE.apk
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: iFunnyDL
          path: iFunnyDL-${{ env.CURRENT_DATE }}.apk

      - name: Release APK
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            iFunnyDL-${{ env.CURRENT_DATE }}.apk
          body: " \n\nDownload ``iFunnyDL-${{ env.CURRENT_DATE }}.apk`` and install it on your android device. Share an iFunny post to the app or paste a link into the URL box and it'll download it to Pictures/iFunnyDL."
          append_body: true
          draft: false
          prerelease: false
        if: github.event_name == 'release'